apiVersion: apps/v1
kine: Deployment
metadata:
	name: statetracker-deployment
spec:
  replicas: 3
	selector:
		matchLabels:
      app: statetracker-pod
  template:
    metadata:
      labels:
        app: statetracker-pod
    spec:
      containers:
        - name: statetracker-container
          image: statetracker:1.0.0
          volumeMounts:
            - name: log
              mountPath: /CoreLogs
          ports:
            - containerPort: 80
          env:
            # Global
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: ASPNETCORE_URLS
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: ASPNETCORE_Kestrel__Certificates__Default__Password
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: ASPNETCORE_Kestrel__Certificates__Default__Path
            # Elastic
            - name: Elastic-Host
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: Elastic-Host
            - name: Elastic-Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: Elastic-Username
            - name: Elastic-Password
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: Elastic-Password
            - name: Elastic-Index
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: StateTracker-Elastic-Index
            # RabbitMQ
            - name: E-RabbitMQ-Host
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: E-RabbitMQ-Host
            - name: E-RabbitMQ-Port
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: E-RabbitMQ-Port
            - name: E-RabbitMQ-Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: E-RabbitMQ-Username
            - name: E-RabbitMQ-Password
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: E-RabbitMQ-Password
            # Mongo
            - name: MongoConnectionString
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: StateTracker-MongoConnectionString
            # Core
            - name: Host
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: StateTracker-Host
            - name: Port
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: StateTracker-Port
    volumes:
      - name: log
        emptyDir: {}